package nc.uap.lfw.perspective.webcomponent;

import nc.lfw.lfwtools.perspective.MainPlugin;
import nc.uap.lfw.core.WEBPersPlugin;

import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.swt.graphics.Image;

public class ImageProvider {
	public static Image uinodes = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "uinodes.png")).createImage();
	public static Image refnode = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "refnode.gif")).createImage();
	public static Image uinode = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "uinode.png")).createImage();
	public static Image src = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "src.png")).createImage();
	public static Image wfm = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "platform.png")).createImage();
	public static Image template = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "template.png")).createImage();
	public static Image query = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "template-query.png")).createImage();
	public static Image print = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "template-out.png")).createImage();
	public static Image mlr = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "page_state.gif")).createImage();
	public static Image service = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "property.png")).createImage();
	public static Image editor = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "editor.gif")).createImage();
	public static Image doc = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "doc.png")).createImage();
	public static Image pageflow = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "pageflow.gif")).createImage();
	public static Image pages = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "pages.gif")).createImage();
	public static Image page = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "page.gif")).createImage();
	public static Image page_state = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "page_state.gif")).createImage();
	public static Image fmodel = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "fmodel.png")).createImage();
	public static Image fmodel_function = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "fmodel-function.png")).createImage();
	public static Image fmodel_menu = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "fmodel-menu.png")).createImage();
	public static Image widget = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "widget.gif")).createImage();
//	public static Image about = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBProjPlugin.ICONS_PATH, "about.png")).createImage();
	public static Image file = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "file.png")).createImage();
	public static Image key = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "keyProperty.gif")).createImage();
	public static Image property = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "property.png")).createImage();
	public static Image groups = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "groups.gif")).createImage();
	public static Image listener = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "listener.gif")).createImage();
	public static Image bc = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "bc.png")).createImage();
	public static Image combodata = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "combodata.gif")).createImage();
	public static Image menubar = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "menubar.gif")).createImage();
	public static Image form = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "form.gif")).createImage();
	public static Image refds = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "refds.gif")).createImage();
	public static Image ds = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "ds.gif")).createImage();
	public static Image metadata = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "metadata.png")).createImage();
	public static Image editorb = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "editor.ico")).createImage();
	public static Image bpf = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "bpf.png")).createImage();
	public static Image virtualdir = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "virtualdir.gif")).createImage();
	public static Image component = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "component.gif")).createImage();
	public static Image simplequery = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "query1.png")).createImage();
	public static Image advquery = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "query2.png")).createImage();
	public static Image advflowquery = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "query3.png")).createImage();
	public static Image module = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "module.gif")).createImage();
	public static Image mdclass = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "mdclass.gif")).createImage();
	public static Image create = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "create.gif")).createImage();
	public static Image dialog = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "dialog.gif")).createImage();
	public static Image error = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "err.gif")).createImage();
	public static Image checked = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "checked.gif")).createImage();
	public static Image unchecked = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "unchecked.gif")).createImage();
	public static Image func = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "func.gif")).createImage();
	public static Image portalpage = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "portalpage.gif")).createImage();
	public static Image portlet = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "portlet.gif")).createImage();
	public static Image skin = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "skin.gif")).createImage();
	public static Image refforder = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "businesscomp.gif")).createImage();
	public static Image cardwin = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "cardwin.jpg")).createImage();
	public static Image cardwin_wfm = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "cardwin_wfm.jpg")).createImage();
	public static Image listwin_nonorg = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "listwin_nonorg.jpg")).createImage();
	public static Image listwin_org = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "listwin_org.jpg")).createImage();
	public static Image okcancel = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "okcancel.jpg")).createImage();
	public static Image saveadd = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "saveadd.jpg")).createImage();
	public static Image start = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "start.gif")).createImage();
	public static Image succeed = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "succeed.png")).createImage();
	public static Image wait = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "wait.png")).createImage();
	public static Image fail = ImageDescriptor.createFromURL(MainPlugin.makeImageURL(WEBPersPlugin.ICONS_PATH, "fail.png")).createImage();
	
}
