/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpAppsCategoryVO extends SuperVO {
	private nc.vo.pub.lang.UFBoolean activeflag;
	private java.lang.String id;
	private java.lang.String i18nname;
	private java.lang.String pk_module;
	private java.lang.String pk_parent;
	private java.lang.String pk_appscategory;
	private java.lang.String title;
	private java.lang.String title2;
	private java.lang.String title3;
	private java.lang.String title4;
	private java.lang.String title5;
	private java.lang.String title6;
	private java.lang.String ext1;
	private java.lang.String ext2;
	private java.lang.String ext3;
	private java.lang.String ext4;
	private java.lang.String ext5;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String ACTIVEFLAG = "activeflag";
	public static final String ID = "id";
	public static final String I18NNAME = "i18nname";
	public static final String PK_MODULE = "pk_module";
	public static final String PK_PARENT = "pk_parent";
	public static final String PK_APPSCATEGORY = "pk_appscategory";
	public static final String TITLE = "title";
	public static final String TITLE2 = "title2";
	public static final String TITLE3 = "title3";
	public static final String TITLE4 = "title4";
	public static final String TITLE5 = "title5";
	public static final String TITLE6 = "title6";
	public static final String EXT1 = "ext1";
	public static final String EXT2 = "ext2";
	public static final String EXT3 = "ext3";
	public static final String EXT4 = "ext4";
	public static final String EXT5 = "ext5";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
			
	/**
	 * 属性activeflag的Getter方法.属性名：是否启用
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getActiveflag () {
		return activeflag;
	}   
	/**
	 * 属性activeflag的Setter方法.属性名：是否启用
	 * 创建日期:
	 * @param newActiveflag nc.vo.pub.lang.UFBoolean
	 */
	public void setActiveflag (nc.vo.pub.lang.UFBoolean newActiveflag ) {
	 	this.activeflag = newActiveflag;
	} 	  
	/**
	 * 属性id的Getter方法.属性名：编号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getId () {
		return id;
	}   
	/**
	 * 属性id的Setter方法.属性名：编号
	 * 创建日期:
	 * @param newId java.lang.String
	 */
	public void setId (java.lang.String newId ) {
	 	this.id = newId;
	} 	  
	/**
	 * 属性i18nname的Getter方法.属性名：多语名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getI18nname () {
		return i18nname;
	}   
	/**
	 * 属性i18nname的Setter方法.属性名：多语名称
	 * 创建日期:
	 * @param newI18nname java.lang.String
	 */
	public void setI18nname (java.lang.String newI18nname ) {
	 	this.i18nname = newI18nname;
	} 	  
	/**
	 * 属性pk_module的Getter方法.属性名：模块
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_module () {
		return pk_module;
	}   
	/**
	 * 属性pk_module的Setter方法.属性名：模块
	 * 创建日期:
	 * @param newPk_module java.lang.String
	 */
	public void setPk_module (java.lang.String newPk_module ) {
	 	this.pk_module = newPk_module;
	} 	  
	/**
	 * 属性pk_parent的Getter方法.属性名：上级分组
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parent () {
		return pk_parent;
	}   
	/**
	 * 属性pk_parent的Setter方法.属性名：上级分组
	 * 创建日期:
	 * @param newPk_parent java.lang.String
	 */
	public void setPk_parent (java.lang.String newPk_parent ) {
	 	this.pk_parent = newPk_parent;
	} 	  
	/**
	 * 属性pk_appscategory的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_appscategory () {
		return pk_appscategory;
	}   
	/**
	 * 属性pk_appscategory的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_appscategory java.lang.String
	 */
	public void setPk_appscategory (java.lang.String newPk_appscategory ) {
	 	this.pk_appscategory = newPk_appscategory;
	} 	  
	/**
	 * 属性title的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性title2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle2 () {
		return title2;
	}   
	/**
	 * 属性title2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle2 java.lang.String
	 */
	public void setTitle2 (java.lang.String newTitle2 ) {
	 	this.title2 = newTitle2;
	} 	  
	/**
	 * 属性title3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle3 () {
		return title3;
	}   
	/**
	 * 属性title3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle3 java.lang.String
	 */
	public void setTitle3 (java.lang.String newTitle3 ) {
	 	this.title3 = newTitle3;
	} 	  
	/**
	 * 属性title4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle4 () {
		return title4;
	}   
	/**
	 * 属性title4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle4 java.lang.String
	 */
	public void setTitle4 (java.lang.String newTitle4 ) {
	 	this.title4 = newTitle4;
	} 	  
	/**
	 * 属性title5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle5 () {
		return title5;
	}   
	/**
	 * 属性title5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle5 java.lang.String
	 */
	public void setTitle5 (java.lang.String newTitle5 ) {
	 	this.title5 = newTitle5;
	} 	  
	/**
	 * 属性title6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle6 () {
		return title6;
	}   
	/**
	 * 属性title6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle6 java.lang.String
	 */
	public void setTitle6 (java.lang.String newTitle6 ) {
	 	this.title6 = newTitle6;
	} 	  
	/**
	 * 属性ext1的Getter方法.属性名：扩展项1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt1 () {
		return ext1;
	}   
	/**
	 * 属性ext1的Setter方法.属性名：扩展项1
	 * 创建日期:
	 * @param newExt1 java.lang.String
	 */
	public void setExt1 (java.lang.String newExt1 ) {
	 	this.ext1 = newExt1;
	} 	  
	/**
	 * 属性ext2的Getter方法.属性名：扩展项2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt2 () {
		return ext2;
	}   
	/**
	 * 属性ext2的Setter方法.属性名：扩展项2
	 * 创建日期:
	 * @param newExt2 java.lang.String
	 */
	public void setExt2 (java.lang.String newExt2 ) {
	 	this.ext2 = newExt2;
	} 	  
	/**
	 * 属性ext3的Getter方法.属性名：扩展项3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt3 () {
		return ext3;
	}   
	/**
	 * 属性ext3的Setter方法.属性名：扩展项3
	 * 创建日期:
	 * @param newExt3 java.lang.String
	 */
	public void setExt3 (java.lang.String newExt3 ) {
	 	this.ext3 = newExt3;
	} 	  
	/**
	 * 属性ext4的Getter方法.属性名：扩展项4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt4 () {
		return ext4;
	}   
	/**
	 * 属性ext4的Setter方法.属性名：扩展项4
	 * 创建日期:
	 * @param newExt4 java.lang.String
	 */
	public void setExt4 (java.lang.String newExt4 ) {
	 	this.ext4 = newExt4;
	} 	  
	/**
	 * 属性ext5的Getter方法.属性名：扩展项5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getExt5 () {
		return ext5;
	}   
	/**
	 * 属性ext5的Setter方法.属性名：扩展项5
	 * 创建日期:
	 * @param newExt5 java.lang.String
	 */
	public void setExt5 (java.lang.String newExt5 ) {
	 	this.ext5 = newExt5;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_appscategory";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_appscategory";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_appscategory";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpAppsCategoryVO() {
		super();	
	}    
} 


