/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpMenuCategoryVO extends SuperVO {
	private nc.vo.pub.lang.UFBoolean activeflag;
	private java.lang.String pk_menucategory;
	private java.lang.String title;
	private java.lang.String title2;
	private java.lang.String title3;
	private java.lang.String title4;
	private java.lang.String title5;
	private java.lang.String title6;
	private java.lang.String id;
	private java.lang.String ordernum;
	private java.lang.String filterclass;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String ACTIVEFLAG = "activeflag";
	public static final String PK_MENUCATEGORY = "pk_menucategory";
	public static final String TITLE = "title";
	public static final String TITLE2 = "title2";
	public static final String TITLE3 = "title3";
	public static final String TITLE4 = "title4";
	public static final String TITLE5 = "title5";
	public static final String TITLE6 = "title6";
	public static final String ID = "id";
	public static final String ORDERNUM = "ordernum";
	public static final String FILTERCLASS = "filterclass";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
			
	/**
	 * 属性activeflag的Getter方法.属性名：是否启用
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getActiveflag () {
		return activeflag;
	}   
	/**
	 * 属性activeflag的Setter方法.属性名：是否启用
	 * 创建日期:
	 * @param newActiveflag nc.vo.pub.lang.UFBoolean
	 */
	public void setActiveflag (nc.vo.pub.lang.UFBoolean newActiveflag ) {
	 	this.activeflag = newActiveflag;
	} 	  
	/**
	 * 属性pk_menucategory的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_menucategory () {
		return pk_menucategory;
	}   
	/**
	 * 属性pk_menucategory的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_menucategory java.lang.String
	 */
	public void setPk_menucategory (java.lang.String newPk_menucategory ) {
	 	this.pk_menucategory = newPk_menucategory;
	} 	  
	/**
	 * 属性title的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性title2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle2 () {
		return title2;
	}   
	/**
	 * 属性title2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle2 java.lang.String
	 */
	public void setTitle2 (java.lang.String newTitle2 ) {
	 	this.title2 = newTitle2;
	} 	  
	/**
	 * 属性title3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle3 () {
		return title3;
	}   
	/**
	 * 属性title3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle3 java.lang.String
	 */
	public void setTitle3 (java.lang.String newTitle3 ) {
	 	this.title3 = newTitle3;
	} 	  
	/**
	 * 属性title4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle4 () {
		return title4;
	}   
	/**
	 * 属性title4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle4 java.lang.String
	 */
	public void setTitle4 (java.lang.String newTitle4 ) {
	 	this.title4 = newTitle4;
	} 	  
	/**
	 * 属性title5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle5 () {
		return title5;
	}   
	/**
	 * 属性title5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle5 java.lang.String
	 */
	public void setTitle5 (java.lang.String newTitle5 ) {
	 	this.title5 = newTitle5;
	} 	  
	/**
	 * 属性title6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTitle6 () {
		return title6;
	}   
	/**
	 * 属性title6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newTitle6 java.lang.String
	 */
	public void setTitle6 (java.lang.String newTitle6 ) {
	 	this.title6 = newTitle6;
	} 	  
	/**
	 * 属性id的Getter方法.属性名：编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getId () {
		return id;
	}   
	/**
	 * 属性id的Setter方法.属性名：编码
	 * 创建日期:
	 * @param newId java.lang.String
	 */
	public void setId (java.lang.String newId ) {
	 	this.id = newId;
	} 	  
	/**
	 * 属性ordernum的Getter方法.属性名：排序号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrdernum () {
		return ordernum;
	}   
	/**
	 * 属性ordernum的Setter方法.属性名：排序号
	 * 创建日期:
	 * @param newOrdernum java.lang.String
	 */
	public void setOrdernum (java.lang.String newOrdernum ) {
	 	this.ordernum = newOrdernum;
	} 	  
	/**
	 * 属性filterclass的Getter方法.属性名：过滤器
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFilterclass () {
		return filterclass;
	}   
	/**
	 * 属性filterclass的Setter方法.属性名：过滤器
	 * 创建日期:
	 * @param newFilterclass java.lang.String
	 */
	public void setFilterclass (java.lang.String newFilterclass ) {
	 	this.filterclass = newFilterclass;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_menucategory";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_menucategory";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_menucategory";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpMenuCategoryVO() {
		super();	
	}    
} 


