/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.cpb.org.vos;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CpMenuItemVO extends SuperVO {
	private java.lang.String pk_funnode;
	private java.lang.String iconpath;
	private nc.vo.pub.lang.UFBoolean isnotleaf;
	private java.lang.String menuitemdes;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String name2;
	private java.lang.String name3;
	private java.lang.String name4;
	private java.lang.String name5;
	private java.lang.String name6;
	private java.lang.String pk_menucategory;
	private java.lang.String pk_menuitem;
	private java.lang.String pk_parent;
	private java.lang.String ordernum;
	private java.lang.String providerclass;
	private nc.vo.pub.lang.UFBoolean isofen;
	private nc.vo.pub.lang.UFBoolean isnewpage;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private String winid;

	public static final String PK_FUNNODE = "pk_funnode";
	public static final String ICONPATH = "iconpath";
	public static final String ISNOTLEAF = "isnotleaf";
	public static final String MENUITEMDES = "menuitemdes";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String NAME2 = "name2";
	public static final String NAME3 = "name3";
	public static final String NAME4 = "name4";
	public static final String NAME5 = "name5";
	public static final String NAME6 = "name6";
	public static final String PK_MENUCATEGORY = "pk_menucategory";
	public static final String PK_MENUITEM = "pk_menuitem";
	public static final String PK_PARENT = "pk_parent";
	public static final String ORDERNUM = "ordernum";
	public static final String PROVIDERCLASS = "providerclass";
	public static final String ISOFEN = "isofen";
	public static final String ISNEWPAGE = "isnewpage";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String WINID = "winid";
	
	/**
	 * 属性pk_funnode的Getter方法.属性名：功能节点
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_funnode () {
		return pk_funnode;
	}   
	/**
	 * 属性pk_funnode的Setter方法.属性名：功能节点
	 * 创建日期:
	 * @param newPk_funnode java.lang.String
	 */
	public void setPk_funnode (java.lang.String newPk_funnode ) {
	 	this.pk_funnode = newPk_funnode;
	} 	  
	/**
	 * 属性iconpath的Getter方法.属性名：图标路径
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getIconpath () {
		return iconpath;
	}   
	/**
	 * 属性iconpath的Setter方法.属性名：图标路径
	 * 创建日期:
	 * @param newIconpath java.lang.String
	 */
	public void setIconpath (java.lang.String newIconpath ) {
	 	this.iconpath = newIconpath;
	} 	  
	/**
	 * 属性isnotleaf的Getter方法.属性名：是否虚目录
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnotleaf () {
		return isnotleaf;
	}   
	/**
	 * 属性isnotleaf的Setter方法.属性名：是否虚目录
	 * 创建日期:
	 * @param newIsnotleaf nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnotleaf (nc.vo.pub.lang.UFBoolean newIsnotleaf ) {
	 	this.isnotleaf = newIsnotleaf;
	} 	  
	/**
	 * 属性menuitemdes的Getter方法.属性名：描述
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMenuitemdes () {
		return menuitemdes;
	}   
	/**
	 * 属性menuitemdes的Setter方法.属性名：描述
	 * 创建日期:
	 * @param newMenuitemdes java.lang.String
	 */
	public void setMenuitemdes (java.lang.String newMenuitemdes ) {
	 	this.menuitemdes = newMenuitemdes;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性name2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName2 () {
		return name2;
	}   
	/**
	 * 属性name2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName2 java.lang.String
	 */
	public void setName2 (java.lang.String newName2 ) {
	 	this.name2 = newName2;
	} 	  
	/**
	 * 属性name3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName3 () {
		return name3;
	}   
	/**
	 * 属性name3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName3 java.lang.String
	 */
	public void setName3 (java.lang.String newName3 ) {
	 	this.name3 = newName3;
	} 	  
	/**
	 * 属性name4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName4 () {
		return name4;
	}   
	/**
	 * 属性name4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName4 java.lang.String
	 */
	public void setName4 (java.lang.String newName4 ) {
	 	this.name4 = newName4;
	} 	  
	/**
	 * 属性name5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName5 () {
		return name5;
	}   
	/**
	 * 属性name5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName5 java.lang.String
	 */
	public void setName5 (java.lang.String newName5 ) {
	 	this.name5 = newName5;
	} 	  
	/**
	 * 属性name6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName6 () {
		return name6;
	}   
	/**
	 * 属性name6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName6 java.lang.String
	 */
	public void setName6 (java.lang.String newName6 ) {
	 	this.name6 = newName6;
	} 	  
	/**
	 * 属性pk_menucategory的Getter方法.属性名：分组
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_menucategory () {
		return pk_menucategory;
	}   
	/**
	 * 属性pk_menucategory的Setter方法.属性名：分组
	 * 创建日期:
	 * @param newPk_menucategory java.lang.String
	 */
	public void setPk_menucategory (java.lang.String newPk_menucategory ) {
	 	this.pk_menucategory = newPk_menucategory;
	} 	  
	/**
	 * 属性pk_menuitem的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_menuitem () {
		return pk_menuitem;
	}   
	/**
	 * 属性pk_menuitem的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_menuitem java.lang.String
	 */
	public void setPk_menuitem (java.lang.String newPk_menuitem ) {
	 	this.pk_menuitem = newPk_menuitem;
	} 	  
	/**
	 * 属性pk_parent的Getter方法.属性名：上级菜单项
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parent () {
		return pk_parent;
	}   
	/**
	 * 属性pk_parent的Setter方法.属性名：上级菜单项
	 * 创建日期:
	 * @param newPk_parent java.lang.String
	 */
	public void setPk_parent (java.lang.String newPk_parent ) {
	 	this.pk_parent = newPk_parent;
	} 	  
	/**
	 * 属性ordernum的Getter方法.属性名：排序号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOrdernum () {
		return ordernum;
	}   
	/**
	 * 属性ordernum的Setter方法.属性名：排序号
	 * 创建日期:
	 * @param newOrdernum java.lang.String
	 */
	public void setOrdernum (java.lang.String newOrdernum ) {
	 	this.ordernum = newOrdernum;
	} 	  
	/**
	 * 属性providerclass的Getter方法.属性名：提供服务类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getProviderclass () {
		return providerclass;
	}   
	/**
	 * 属性providerclass的Setter方法.属性名：提供服务类
	 * 创建日期:
	 * @param newProviderclass java.lang.String
	 */
	public void setProviderclass (java.lang.String newProviderclass ) {
	 	this.providerclass = newProviderclass;
	} 	  
	/**
	 * 属性isofen的Getter方法.属性名：是否常用
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsofen () {
		return isofen;
	}   
	/**
	 * 属性isofen的Setter方法.属性名：是否常用
	 * 创建日期:
	 * @param newIsofen nc.vo.pub.lang.UFBoolean
	 */
	public void setIsofen (nc.vo.pub.lang.UFBoolean newIsofen ) {
	 	this.isofen = newIsofen;
	} 	  
	/**
	 * 属性isnewpage的Getter方法.属性名：在新窗口打开
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsnewpage () {
		return isnewpage;
	}   
	/**
	 * 属性isnewpage的Setter方法.属性名：在新窗口打开
	 * 创建日期:
	 * @param newIsnewpage nc.vo.pub.lang.UFBoolean
	 */
	public void setIsnewpage (nc.vo.pub.lang.UFBoolean newIsnewpage ) {
	 	this.isnewpage = newIsnewpage;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_menuitem";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "cp_menuitem";
	}    
	
	public String getWinid() {
		return winid;
	}
	public void setWinid(String winid) {
		this.winid = winid;
	}
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "cp_menuitem";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public CpMenuItemVO() {
		super();	
	}    
} 


