/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.wfm.vo;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
import java.util.HashMap;
import java.util.Map;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WfmFlwCatVO extends SuperVO {
	private java.lang.String pk_flwcat;
	private java.lang.String catname;
	private java.lang.String catname2;
	private java.lang.String catname3;
	private java.lang.String catname4;
	private java.lang.String catname5;
	private java.lang.String catname6;
	private java.lang.String catcode;
	private java.lang.String serverclass;
	private java.lang.String devmodule;
	private java.lang.String devcomponent;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_FLWCAT = "pk_flwcat";
	public static final String CATNAME = "catname";
	public static final String CATNAME2 = "catname2";
	public static final String CATNAME3 = "catname3";
	public static final String CATNAME4 = "catname4";
	public static final String CATNAME5 = "catname5";
	public static final String CATNAME6 = "catname6";
	public static final String CATCODE = "catcode";
	public static final String SERVERCLASS = "serverclass";
	public static final String DEVMODULE = "devmodule";
	public static final String DEVCOMPONENT = "devcomponent";
			
	/**
	 * 属性pk_flwcat的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_flwcat () {
		return pk_flwcat;
	}   
	/**
	 * 属性pk_flwcat的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_flwcat java.lang.String
	 */
	public void setPk_flwcat (java.lang.String newPk_flwcat ) {
	 	this.pk_flwcat = newPk_flwcat;
	} 	  
	/**
	 * 属性catname的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCatname () {
		return catname;
	}   
	/**
	 * 属性catname的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newCatname java.lang.String
	 */
	public void setCatname (java.lang.String newCatname ) {
	 	this.catname = newCatname;
	} 	  
	/**
	 * 属性catname2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCatname2 () {
		return catname2;
	}   
	/**
	 * 属性catname2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newCatname2 java.lang.String
	 */
	public void setCatname2 (java.lang.String newCatname2 ) {
	 	this.catname2 = newCatname2;
	} 	  
	/**
	 * 属性catname3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCatname3 () {
		return catname3;
	}   
	/**
	 * 属性catname3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newCatname3 java.lang.String
	 */
	public void setCatname3 (java.lang.String newCatname3 ) {
	 	this.catname3 = newCatname3;
	} 	  
	/**
	 * 属性catname4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCatname4 () {
		return catname4;
	}   
	/**
	 * 属性catname4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newCatname4 java.lang.String
	 */
	public void setCatname4 (java.lang.String newCatname4 ) {
	 	this.catname4 = newCatname4;
	} 	  
	/**
	 * 属性catname5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCatname5 () {
		return catname5;
	}   
	/**
	 * 属性catname5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newCatname5 java.lang.String
	 */
	public void setCatname5 (java.lang.String newCatname5 ) {
	 	this.catname5 = newCatname5;
	} 	  
	/**
	 * 属性catname6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCatname6 () {
		return catname6;
	}   
	/**
	 * 属性catname6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newCatname6 java.lang.String
	 */
	public void setCatname6 (java.lang.String newCatname6 ) {
	 	this.catname6 = newCatname6;
	} 	  
	/**
	 * 属性catcode的Getter方法.属性名：大类编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCatcode () {
		return catcode;
	}   
	/**
	 * 属性catcode的Setter方法.属性名：大类编码
	 * 创建日期:
	 * @param newCatcode java.lang.String
	 */
	public void setCatcode (java.lang.String newCatcode ) {
	 	this.catcode = newCatcode;
	} 	  
	/**
	 * 属性serverclass的Getter方法.属性名：扩张处理类
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getServerclass () {
		return serverclass;
	}   
	/**
	 * 属性serverclass的Setter方法.属性名：扩张处理类
	 * 创建日期:
	 * @param newServerclass java.lang.String
	 */
	public void setServerclass (java.lang.String newServerclass ) {
	 	this.serverclass = newServerclass;
	} 	  
	/**
	 * 属性devmodule的Getter方法.属性名：开发模块
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDevmodule () {
		return devmodule;
	}   
	/**
	 * 属性devmodule的Setter方法.属性名：开发模块
	 * 创建日期:
	 * @param newDevmodule java.lang.String
	 */
	public void setDevmodule (java.lang.String newDevmodule ) {
	 	this.devmodule = newDevmodule;
	} 	  
	/**
	 * 属性devcomponent的Getter方法.属性名：开发组件
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDevcomponent () {
		return devcomponent;
	}   
	/**
	 * 属性devcomponent的Setter方法.属性名：开发组件
	 * 创建日期:
	 * @param newDevcomponent java.lang.String
	 */
	public void setDevcomponent (java.lang.String newDevcomponent ) {
	 	this.devcomponent = newDevcomponent;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_flwcat";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wfm_flwcat";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wfm_flwcat";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WfmFlwCatVO() {
		super();	
	}    
} 


